spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-zxs-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-zxs-test
#请以utf-8格式保存